-- Phase 2: Analytics, Funnel, and Pricing Extensions
-- Backward-compatible additions to existing schema

-- ============================================================================
-- Book Analytics Aggregations
-- ============================================================================
-- Pre-computed daily/weekly/monthly sales aggregations per book
-- Allows fast queries for date-range filtering without scanning all sales_events

create table if not exists public.book_analytics_daily (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles (id) on delete cascade,
  book_id uuid references public.books (id) on delete cascade,
  date date not null,
  revenue numeric(12,2) not null default 0,
  units_sold integer not null default 0,
  platform text not null,
  created_at timestamptz not null default timezone('utc'::text, now()),
  unique (book_id, date, platform)
);

create index if not exists book_analytics_daily_book_idx on public.book_analytics_daily (book_id, date desc);
create index if not exists book_analytics_daily_profile_idx on public.book_analytics_daily (profile_id, date desc);

-- ============================================================================
-- Reader Funnel Events
-- ============================================================================
-- Manual tracking of impressions → clicks → conversions
-- Phase 2: Manual entry only; Phase 3+: Automated tracking via pixels/webhooks

create table if not exists public.funnel_events (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles (id) on delete cascade,
  book_id uuid references public.books (id) on delete set null,
  event_type text not null check (event_type in ('impression', 'click', 'conversion')),
  source text not null, -- e.g., 'facebook_ad', 'email_campaign', 'organic'
  metadata jsonb not null default '{}'::jsonb, -- Extensible for future tracking params
  occurred_at timestamptz not null default timezone('utc'::text, now()),
  created_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists funnel_events_profile_idx on public.funnel_events (profile_id, occurred_at desc);
create index if not exists funnel_events_book_idx on public.funnel_events (book_id, event_type, occurred_at);

-- ============================================================================
-- Pricing History & Recommendations
-- ============================================================================
-- Tracks price changes over time for each book
-- Enables rule-based pricing suggestions

create table if not exists public.pricing_snapshots (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles (id) on delete cascade,
  book_id uuid not null references public.books (id) on delete cascade,
  platform text not null,
  price numeric(10,2) not null,
  currency text not null default 'USD',
  snapshot_date date not null default current_date,
  created_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists pricing_snapshots_book_idx on public.pricing_snapshots (book_id, snapshot_date desc);
create index if not exists pricing_snapshots_platform_idx on public.pricing_snapshots (book_id, platform, snapshot_date desc);

-- ============================================================================
-- Pricing Recommendations Cache
-- ============================================================================
-- Rule-based suggestions generated by pricing helper
-- Cached to avoid recalculation on every page load

create table if not exists public.pricing_recommendations (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles (id) on delete cascade,
  book_id uuid not null references public.books (id) on delete cascade,
  recommendation_type text not null check (recommendation_type in ('increase', 'decrease', 'revert', 'maintain')),
  suggested_price numeric(10,2),
  reasoning text not null, -- Human-readable explanation
  metadata jsonb not null default '{}'::jsonb, -- Data used for calculation
  generated_at timestamptz not null default timezone('utc'::text, now()),
  expires_at timestamptz not null default (timezone('utc'::text, now()) + interval '24 hours')
);

create index if not exists pricing_recommendations_book_idx on public.pricing_recommendations (book_id, generated_at desc);
create index if not exists pricing_recommendations_expires_idx on public.pricing_recommendations (expires_at);

-- ============================================================================
-- Helper Views for Common Queries
-- ============================================================================

-- Aggregate book analytics by week
create or replace view public.book_analytics_weekly as
select
  book_id,
  profile_id,
  platform,
  date_trunc('week', date) as week_start,
  sum(revenue) as revenue,
  sum(units_sold) as units_sold
from public.book_analytics_daily
group by book_id, profile_id, platform, week_start;

-- Aggregate book analytics by month
create or replace view public.book_analytics_monthly as
select
  book_id,
  profile_id,
  platform,
  date_trunc('month', date) as month_start,
  sum(revenue) as revenue,
  sum(units_sold) as units_sold
from public.book_analytics_daily
group by book_id, profile_id, platform, month_start;

-- Funnel conversion rates
create or replace view public.funnel_conversion_summary as
select
  profile_id,
  book_id,
  source,
  count(*) filter (where event_type = 'impression') as impressions,
  count(*) filter (where event_type = 'click') as clicks,
  count(*) filter (where event_type = 'conversion') as conversions,
  case
    when count(*) filter (where event_type = 'impression') > 0
    then (count(*) filter (where event_type = 'click')::numeric / count(*) filter (where event_type = 'impression')) * 100
    else 0
  end as click_through_rate,
  case
    when count(*) filter (where event_type = 'click') > 0
    then (count(*) filter (where event_type = 'conversion')::numeric / count(*) filter (where event_type = 'click')) * 100
    else 0
  end as conversion_rate
from public.funnel_events
group by profile_id, book_id, source;

-- ============================================================================
-- Cleanup Job for Expired Recommendations
-- ============================================================================

create or replace function public.cleanup_expired_pricing_recommendations()
returns void as $$
begin
  delete from public.pricing_recommendations
  where expires_at < timezone('utc'::text, now());
end;
$$ language plpgsql security definer;

-- Note: Schedule via cron or periodic job (e.g., QStash)
-- Example: SELECT cron.schedule('cleanup-pricing', '0 2 * * *', 'SELECT public.cleanup_expired_pricing_recommendations()');
